CREATE TABLE IF NOT EXISTS t_user
(
    uid      INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(18) NOT NULL UNIQUE,
    nickname VARCHAR(18) NOT NULL,
    password CHAR(64)    NOT NULL COMMENT 'SHA256',
    salt     CHAR(36)    NOT NULL
) ENGINE INNODB
  CHARACTER SET utf8mb4;